import AppKit
import Foundation
import Combine
import OSLog

struct ClipboardSource {
    let bundleIdentifier: String?
    let name: String?

    static var frontmost: ClipboardSource {
        let app = NSWorkspace.shared.frontmostApplication
        return ClipboardSource(bundleIdentifier: app?.bundleIdentifier, name: app?.localizedName)
    }
}

@MainActor
final class ClipboardMonitor {
    private let store: ClipboardStore
    private let settings: AppSettings
    private let pasteboard: ClipboardAccess
    private let source: () -> ClipboardSource
    private let now: () -> Date
    private let recognizer: ImageRecognizing
    private var recognitionTasks: [UUID: Task<Void, Never>] = [:]
    private var itemsSubscription: AnyCancellable?
    private let logger = Logger(subsystem: "com.clipboardnative.macos", category: "recognition")
    private var timer: Timer?
    private var lastChangeCount: Int
    private var ignoredChangeCount: Int?

    init(
        store: ClipboardStore, settings: AppSettings = .shared,
        pasteboard: ClipboardAccess = SystemClipboard(), source: @escaping () -> ClipboardSource = { .frontmost },
        now: @escaping () -> Date = Date.init, recognizer: ImageRecognizing = ImageRecognitionService()
    ) {
        self.store = store
        self.settings = settings
        self.pasteboard = pasteboard
        self.source = source
        self.now = now
        self.recognizer = recognizer
        lastChangeCount = pasteboard.changeCount
        itemsSubscription = store.$items.sink { [weak self] items in
            guard let self else { return }
            let live = Set(items.map(\.id))
            for id in Array(self.recognitionTasks.keys) where !live.contains(id) {
                self.recognitionTasks.removeValue(forKey: id)?.cancel()
            }
        }
    }

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.45, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        recognitionTasks.values.forEach { $0.cancel() }
        recognitionTasks.removeAll()
    }

    func ignoreCurrentChange() { ignoredChangeCount = pasteboard.changeCount }

    func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        if ignoredChangeCount == pasteboard.changeCount { ignoredChangeCount = nil; return }
        guard !settings.isPaused else { return }

        let typeNames = Set((pasteboard.types ?? []).map(\.rawValue))
        let privateTypes = [
            "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType",
        ]
        guard privateTypes.allSatisfy({ !typeNames.contains($0) }) else { return }

        let app = source()
        guard app.bundleIdentifier != Bundle.main.bundleIdentifier,
            !settings.excludedBundleIDs.contains(app.bundleIdentifier ?? "")
        else { return }

        let date = now()
        let base = (date, app.bundleIdentifier, app.name)

        let urls = pasteboard.fileURLs()
        if !urls.isEmpty {
            let hash = ClipboardItem.hash(parts: urls.map { Data($0.absoluteString.utf8) })
            store.add(
                ClipboardItem(
                    id: UUID(), createdAt: base.0, lastUsedAt: base.0, kind: .file, text: nil, rtfData: nil,
                    htmlData: nil, imageData: nil, fileURLs: urls, sourceBundleIdentifier: base.1,
                    sourceApplicationName: base.2, isPinned: false, useCount: 0, contentHash: hash, customName: nil))
            return
        }

        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), NSImage(data: data) != nil {
            let hash = ClipboardItem.hash(parts: [data])
            let id = store.add(
                ClipboardItem(
                    id: UUID(), createdAt: base.0, lastUsedAt: base.0, kind: .image, text: nil, rtfData: nil,
                    htmlData: nil, imageData: data, fileURLs: [], sourceBundleIdentifier: base.1,
                    sourceApplicationName: base.2, isPinned: false, useCount: 0, contentHash: hash, customName: nil))
            recognize(data, id: id, hash: hash, sourceBundleID: base.1)
            return
        }

        guard let raw = pasteboard.string(forType: .string), !raw.normalizedForClipboard.isEmpty else { return }
        let normalized = raw.normalizedForClipboard
        let hash = ClipboardItem.hash(parts: [Data(normalized.utf8)])
        store.add(
            ClipboardItem(
                id: UUID(), createdAt: base.0, lastUsedAt: base.0, kind: normalized.detectedClipboardKind, text: raw,
                rtfData: pasteboard.data(forType: .rtf), htmlData: pasteboard.data(forType: .html), imageData: nil,
                fileURLs: [], sourceBundleIdentifier: base.1, sourceApplicationName: base.2, isPinned: false,
                useCount: 0, contentHash: hash, customName: nil))
    }

    private func recognize(_ data: Data, id: UUID, hash: String, sourceBundleID: String?) {
        guard recognitionTasks[id] == nil, store.items.contains(where: { $0.id == id }) else { return }
        let recognizer = recognizer
        recognitionTasks[id] = Task { [weak self] in
            do {
                let text = try await recognizer.recognize(data)
                try Task.checkCancellation()
                guard let self else { return }
                self.recognitionTasks[id] = nil
                guard !self.settings.isPaused,
                    !self.settings.excludedBundleIDs.contains(sourceBundleID ?? "")
                else { return }
                self.store.updateRecognizedText(text, id: id, contentHash: hash)
            } catch {
                guard !Task.isCancelled, let self else { return }
                self.recognitionTasks[id] = nil
                self.logger.error("Image recognition failed; the captured image remains available.")
            }
        }
    }

    isolated deinit {
        timer?.invalidate()
        recognitionTasks.values.forEach { $0.cancel() }
    }
}
